# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yxyXFzomGyF2RV_rgpWbjCRzuCawlxwW
"""

from google.colab import drive
drive.mount('/content/gdrive')
import numpy as np

X_train = np.loadtxt("/content/gdrive/MyDrive/Colab Notebooks/Datasets/cifar-10-batches-py/X_train.dat")
y_train = np.loadtxt("/content/gdrive/MyDrive/Colab Notebooks/Datasets/cifar-10-batches-py/y_train.dat")
X_test = np.loadtxt("/content/gdrive/MyDrive/Colab Notebooks/Datasets/cifar-10-batches-py/X_test.dat")
y_test = np.loadtxt("/content/gdrive/MyDrive/Colab Notebooks/Datasets/cifar-10-batches-py/y_test.dat")

print(X_train[1,:])

baseline = 1 / len(X_train) * np.sum(np.power(X_train,13), axis = 0)
MSE = np.sum(np.power((baseline-X_train),2))

print('reading data... Done!')
print('baseline accuracy (MAE)', MSE)